name: Deploy
on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout updates
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.20.1'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: nm-vis-${{ hashFiles('package-lock.json') }}
          restore-keys: nm-vis-
      - name: Install npm dependencies
        run: npm install --ignore-scripts --no-audit
      - name: Build app
        run: npm run build-qic || exit 1
      - name: The build has failed
        if: ${{ failure() }}
        run: 'echo "job failed"'
      - name: Deploy to Server
        run: 'echo "success"'
